import React, { useState, useEffect, useRef } from 'react';

function AvatarIcon({ gender = "male", className = "" }) {
  const skin = "#f0c8a0";
  const hair = gender === "female" ? "#3b2a20" : "#2b2017";
  const shirt = gender === "female" ? "#ec4899" : "#0d9488";
  return (
    <svg viewBox="0 0 100 100" className={className} xmlns="http://www.w3.org/2000/svg">
      <circle cx="50" cy="50" r="50" fill="#0f172a" />
      <circle cx="50" cy="40" r="18" fill={skin} />
      {gender === "female" ? (
        <path d="M28 36 Q28 14 50 14 Q72 14 72 36 Q72 30 64 28 Q60 38 50 38 Q40 38 36 28 Q28 30 28 36 Z" fill={hair} />
      ) : (
        <path d="M30 32 Q30 16 50 16 Q70 16 70 32 L70 26 Q50 18 30 26 Z" fill={hair} />
      )}
      {gender === "female" && (
        <>
          <path d="M26 38 Q24 56 28 64 L32 60 Q30 48 30 38 Z" fill={hair} />
          <path d="M74 38 Q76 56 72 64 L68 60 Q70 48 70 38 Z" fill={hair} />
        </>
      )}
      <path d="M20 100 Q20 70 50 70 Q80 70 80 100 Z" fill={shirt} />
      <path d="M40 70 Q50 80 60 70 L60 76 Q50 86 40 76 Z" fill={skin} />
    </svg>
  );
}

const ALL_ROLES = [
  { value: "Youth Curator / Field Volunteer", label: "Youth Curator / Field Volunteer", desc: "Conducts elder interviews & uploads recordings", color: "teal" },
  { value: "DRR Academic Researcher", label: "DRR Academic Researcher", desc: "Validates knowledge with scientific expertise", color: "indigo" },
  { value: "Regional Local Elder / Interviewee", label: "Local Elder / Knowledge Keeper", desc: "Oral history source & community anchor", color: "amber" },
  { value: "Local Government Representative", label: "Local Government Representative", desc: "Policy liaison & disaster management official", color: "emerald" },
  { value: "NGO / Civil Society Partner", label: "NGO / Civil Society Partner", desc: "Community outreach & grassroots mobilization", color: "purple" },
  { value: "Educator / Curriculum Developer", label: "Educator / Curriculum Developer", desc: "Integrates indigenous knowledge into education", color: "rose" },
  { value: "Journalist / Media Partner", label: "Journalist / Media Partner", desc: "Documents & amplifies community stories", color: "orange" },
  { value: "Tech Developer / Data Analyst", label: "Tech Developer / Data Analyst", desc: "Builds platform tools & data pipelines", color: "cyan" },
];

const initialKnowledgeNodes = [
  { id: "vietnam-danang", title: "Storm Warnings via Coastal Swallows & Sea Colors", location: "Da Nang, Central Vietnam", country: "Vietnam", coordinates: { x: 32, y: 46 }, elderName: "Uncle Tran Van Muoi", elderAge: 76, theme: "Marine & Weather", originalText: "Khi chuồn chuồn bay thấp và chim hải yến tập trung đông ở vách đá, bão sẽ tới trong ba ngày nữa.", englishTranslation: "When dragonflies fly low and sea swallows cluster thickly on coastal cliffs, a storm will arrive in three days. If the sea turns dark, muddy yellow at sunset, boats must be hauled ashore immediately.", japaneseTranslation: "トンボが低く飛び、ウミツバメが海岸の崖に密集すると、3日以内に嵐がやってきます。", warningSigns: ["Dragonflies flying very close to the ground", "Sea swallows gathering in high densities on cliffs", "Sunset sea water turning deep muddy yellow"], scientificValidation: "Low barometric pressure before a storm affects insect wings, forcing them lower. Seabirds detect infrasonic waves generated by distant storms and seek shelter.", expertStatus: "Validated", expertName: "Dr. Nguyen Minh Hoang (DRR Specialist, VAST)", curatedBy: "Trang Hoang (Vietnam Youth Volunteer)" },
  { id: "japan-okinawa", title: "Winter South Wind & Moon Halos", location: "Okinawa, Japan", country: "Japan", coordinates: { x: 70, y: 32 }, elderName: "Grandmother Chiyo Oshiro", elderAge: 82, theme: "Meteorological", originalText: "冬の南風が急に止んで不気味な静けさになったら、数時間後に激しいスコールが来る。", englishTranslation: "If the winter south wind suddenly drops into an eerie quiet, a violent squall will strike within hours. If a halo appears around the moon, do not go out to sea the next day.", japaneseTranslation: "冬の南風が急に止んで不気味な静けさになったら、数時間後に激しいスコールが来る。月を囲む「月のかさ」が出た翌日は、天気が大荒れになるから海に出てはいけないよ。", warningSigns: ["Sudden drop and silence of winter south winds", "Large optical halo surrounding the moon at night"], scientificValidation: "A moon halo is caused by ice crystals in high-altitude cirrostratus clouds, which often precede an approaching warm front and storm system.", expertStatus: "Validated", expertName: "Prof. Kenji Sato (Meteorology Dept, Ryukyu University)", curatedBy: "Yuto (Japan Youth Volunteer)" },
  { id: "philippines-leyte", title: "Hermit Crab Inshore Migrations", location: "Leyte, Philippines", country: "Philippines", coordinates: { x: 45, y: 78 }, elderName: "Tatay Mario Santos", elderAge: 79, theme: "Wildlife Behavior", originalText: "Bago dumating ang malakas na bagyo, ang mga umang ay sabay-sabay na umaalis sa dalampasigan papunta sa matataas na lugar.", englishTranslation: "Before a severe typhoon hits, hermit crabs migrate in large groups away from the shoreline towards higher elevation. They intuitively know when the waters will rise.", japaneseTranslation: "激しい台風が襲来する前に、ヤドカリは一斉に海岸を離れ、高台へと移動します。", warningSigns: ["Mass inland migration of hermit crabs away from high-tide line"], scientificValidation: "Crustaceans are highly sensitive to subtle changes in atmospheric pressure and micro-vibrations caused by ocean swells, triggering migratory behavior before storm surges.", expertStatus: "Validated", expertName: "Dr. Maria Clara (Coastal Ecology Lead, UP Diliman)", curatedBy: "Liyab (Philippines Youth Volunteer)" }
];

const draftPresets = [
  { id: "preset-1", author: "Grandpa Wayan Sugi", age: 81, location: "East Java, Indonesia", dialect: "Indonesian / Javanese", rawInput: "Ketika ikan-ikan karang dalam naik ke permukaan air dangkal dalam jumlah banyak, dan air laut tiba-tiba surut melebihi batas pasang surut bulan biasanya, bumi akan bergetar hebat. Orang tua kami dulu selalu menyuruh kami lari ke bukit." },
  { id: "preset-2", author: "Grandmother Le Thi Canh", age: 85, location: "Quang Tri, Vietnam", dialect: "Central Vietnamese dialect", rawInput: "Hễ cứ thấy kiến lửa làm tổ tít trên cành cây cao, còn kiến đen thì lũ lượt bò ra khỏi hang mang theo trứng chạy lên mái nhà là biết thế nào cũng có lụt lớn, nước ngập sâu lắm." },
  { id: "preset-3", author: "Elder Yoshiharu Tanaka", age: 87, location: "Kochi, Shikoku, Japan", dialect: "Tosa dialect", rawInput: "アコウの葉が夏を待たずに一斉に落ちる年は、大型の台風が直撃して大風が吹き荒れる。植物は嵐が来る季節をあらかじめ感じ取って自ら葉を落とし、身を守るのだ。" }
];

const mockUsers = {
  expert: { username: "dr_hoang", name: "Dr. Nguyen Minh Hoang", role: "DRR Academic Researcher", gender: "male", email: "hoang.nm@vast.vn", phone: "+84 912 345 678", bio: "Senior Researcher at VAST specializing in Coastal Disaster Risk Reduction & Oceanography. 15+ years syncing local lore with physics.", country: "Vietnam" },
  volunteer: { username: "tranght", name: "Trang Hoang", role: "Youth Curator / Field Volunteer", gender: "female", email: "tranght.8924@gmail.com", phone: "+84 987 654 321", bio: "SSEAYP Youth Delegate. Passionate about visiting remote coastal fishing communities and digitizing generational oral legends.", country: "Vietnam" },
  interviewee: { username: "uncle_muoi", name: "Uncle Tran Van Muoi", role: "Regional Local Elder / Interviewee", gender: "male", email: "N/A (Managed via Community Hub)", phone: "Contact via Da Nang Volunteer Hub", bio: "Traditional Sea Reader & Veteran Fisherman in Da Nang. Generational keeper of local wind and wave patterns.", country: "Vietnam" }
};

const ROLE_COLOR = { "Youth Curator / Field Volunteer": "teal", "DRR Academic Researcher": "indigo", "Regional Local Elder / Interviewee": "amber", "Local Government Representative": "emerald", "NGO / Civil Society Partner": "purple", "Educator / Curriculum Developer": "rose", "Journalist / Media Partner": "orange", "Tech Developer / Data Analyst": "cyan" };

export default function App() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [knowledgeList, setKnowledgeList] = useState(initialKnowledgeNodes);
  const [selectedNode, setSelectedNode] = useState(initialKnowledgeNodes[0]);
  const [targetInterviews, setTargetInterviews] = useState(112);
  const [targetVolunteers, setTargetVolunteers] = useState(78);

  const [currentUser, setCurrentUser] = useState(mockUsers.volunteer);
  const [customAvatar, setCustomAvatar] = useState(null);
  const [savedAvatars, setSavedAvatars] = useState({});
  const [avatarUploadError, setAvatarUploadError] = useState("");
  const [isSavingProfile, setIsSavingProfile] = useState(false);
  const [profileSavedMsg, setProfileSavedMsg] = useState("");
  const [bioDraft, setBioDraft] = useState(currentUser.bio);
  const fileInputRef = useRef(null);

  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [authMode, setAuthMode] = useState('login');
  const [loginEmail, setLoginEmail] = useState('');
  const [registerName, setRegisterName] = useState('');
  const [registerEmail, setRegisterEmail] = useState('');
  const [registerCountry, setRegisterCountry] = useState('Vietnam');
  const [registerRole, setRegisterRole] = useState(ALL_ROLES[0].value);
  const [registerGender, setRegisterGender] = useState('male');
  const [authError, setAuthError] = useState('');

  // Map
  const [mapZoom, setMapZoom] = useState(1);
  const [mapPan, setMapPan] = useState({ x: 0, y: 0 });
  const [isDraggingMap, setIsDraggingMap] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });

  // AI Engine
  const [aiStage, setAiStage] = useState('upload'); // 'upload' | 'transcribing' | 'transcribed' | 'processing' | 'done'
  const [uploadedFile, setUploadedFile] = useState(null);
  const [transcriptText, setTranscriptText] = useState('');
  const [transcriptProgress, setTranscriptProgress] = useState(0);
  const [customAuthor, setCustomAuthor] = useState("Grandmother Le Thi Canh");
  const [customAge, setCustomAge] = useState("85");
  const [customLoc, setCustomLoc] = useState("Quang Tri, Vietnam");
  const [processingStep, setProcessingStep] = useState(0);
  const [aiResult, setAiResult] = useState(null);
  const audioInputRef = useRef(null);

  const [pendingSubmissions, setPendingSubmissions] = useState([
    { id: "pending-1", title: "Dragonfly Flight Heights", location: "Ha Tinh, Vietnam", country: "Vietnam", elderName: "Nguyen Van Binh", elderAge: 83, theme: "Weather Observation", originalText: "Chuồn chuồn bay thấp thì mưa, bay cao thì nắng. Nhưng hễ bay rợp trời sát sạt mặt đất là có bão giông sắp ập đến.", englishTranslation: "Dragonflies flying low brings rain, high brings sun. But when they swarm in clouds close to the soil, a fierce storm is on its way.", japaneseTranslation: "トンボが低く飛ぶと雨、高く飛ぶと晴れ。しかし、地面のすぐ近くを群れをなして飛ぶときは、激しい嵐が近づいています。", warningSigns: ["Swarms of dragonflies flying extremely close to the ground"], scientificValidation: "Before storms, low air pressure and high moisture weight down insect wings, forcing dragonflies lower.", curatedBy: "Minh Nguyen", expertStatus: "Pending Review" }
  ]);

  const processingSteps = [
    "Analyzing dialect structure & speaker patterns...",
    "Translating to English (Universal Hub language)...",
    "Translating to Japanese (Regional Partner language)...",
    "Extracting distinct ecological warning indicators...",
    "Cross-referencing with scientific literature database...",
  ];

  useEffect(() => {
    let cancelled = false;
    async function loadAvatar() {
      try {
        const res = await window.storage.get(`avatar:${currentUser.username}`, false);
        if (!cancelled && res && res.value) setSavedAvatars(p => ({ ...p, [currentUser.username]: res.value }));
      } catch {}
    }
    loadAvatar();
    setBioDraft(currentUser.bio);
    setCustomAvatar(null);
    setProfileSavedMsg("");
    return () => { cancelled = true; };
  }, [currentUser.username]);

  const clampPan = (zoom, pan) => {
    const m = (zoom - 1) * 50;
    return { x: Math.max(-m, Math.min(m, pan.x)), y: Math.max(-m, Math.min(m, pan.y)) };
  };
  const handleZoomIn = () => setMapZoom(z => Math.min(4, +(z + 0.5).toFixed(2)));
  const handleZoomOut = () => setMapZoom(z => { const nz = Math.max(1, +(z - 0.5).toFixed(2)); setMapPan(p => clampPan(nz, p)); return nz; });
  const handleResetView = () => { setMapZoom(1); setMapPan({ x: 0, y: 0 }); };
  const handleWheelZoom = e => { e.preventDefault(); const d = e.deltaY > 0 ? -0.25 : 0.25; setMapZoom(z => { const nz = Math.max(1, Math.min(4, +(z + d).toFixed(2))); setMapPan(p => clampPan(nz, p)); return nz; }); };
  const handleMapMouseDown = e => { if (mapZoom <= 1) return; setIsDraggingMap(true); setDragStart({ x: e.clientX - mapPan.x, y: e.clientY - mapPan.y }); };
  const handleMapMouseMove = e => { if (!isDraggingMap) return; setMapPan(clampPan(mapZoom, { x: e.clientX - dragStart.x, y: e.clientY - dragStart.y })); };
  const handleMapMouseUp = () => setIsDraggingMap(false);

  // ---- Audio upload & transcription simulation ----
  const handleAudioUpload = e => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    const validTypes = ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4', 'audio/webm', 'audio/m4a', 'video/mp4'];
    if (!validTypes.some(t => file.type.startsWith('audio/') || file.type.startsWith('video/'))) {
      alert("Please upload a valid audio file (MP3, WAV, OGG, M4A, MP4).");
      return;
    }
    setUploadedFile(file);
    setAiStage('upload');
    setAiResult(null);
    setTranscriptText('');
    setTranscriptProgress(0);
  };

  const handleStartTranscribe = () => {
    setAiStage('transcribing');
    setTranscriptProgress(0);
    const preset = draftPresets[1]; // Simulate with preset 2
    const fullText = preset.rawInput;
    let i = 0;
    const chunk = Math.ceil(fullText.length / 30);
    const interval = setInterval(() => {
      i++;
      const progress = Math.min(100, Math.round((i / 30) * 100));
      setTranscriptProgress(progress);
      setTranscriptText(fullText.slice(0, i * chunk));
      if (i >= 30) {
        clearInterval(interval);
        setTranscriptText(fullText);
        setTranscriptProgress(100);
        setTimeout(() => setAiStage('transcribed'), 400);
      }
    }, 120);
  };

  const handleRunProcess = () => {
    if (aiStage !== 'transcribed' && aiStage !== 'done') return;
    setAiStage('processing');
    setProcessingStep(0);
    const timers = processingSteps.map((_, idx) => setTimeout(() => setProcessingStep(idx + 1), (idx + 1) * 900));
    setTimeout(() => {
      timers.forEach(clearTimeout);
      setAiResult({
        id: "sim-" + Date.now(),
        title: "Ant Colony Elevation Migrations Before Floods",
        theme: "Wildlife & Flood Warning",
        originalText: transcriptText || draftPresets[1].rawInput,
        elderName: customAuthor,
        elderAge: parseInt(customAge) || 80,
        location: customLoc,
        englishTranslation: "Whenever fire ants nest high up on tree branches and black ants carry their eggs in columns out to the roof, know that a major flood is coming — the waters will rise far beyond the normal banks.",
        japaneseTranslation: "赤アリが木の高い枝に巣を作り、黒アリが卵を抱えて屋根へと列をなして移動するのを見かけたら、大洪水の前触れです。水は普段の川岸を大きく越えて溢れます。",
        warningSigns: ["Fire ants building nests abnormally high on tree branches", "Black ants migrating in large lines carrying eggs toward roof-level"],
        scientificValidation: "Ants are highly sensitive to soil saturation and atmospheric humidity changes. Before massive rainfall events, they instinctively relocate their colonies and eggs upward to dry heights.",
        expertStatus: "Pending Review",
        curatedBy: currentUser.name
      });
      setAiStage('done');
    }, processingSteps.length * 900 + 400);
  };

  const submitToExpertQueue = () => {
    if (!aiResult) return;
    setPendingSubmissions(p => [aiResult, ...p]);
    setAiResult(null);
    setAiStage('upload');
    setUploadedFile(null);
    setTranscriptText('');
    alert("Draft sent to Expert Validation Queue!");
  };

  const handleApproveSub = (sub, updatedValidation) => {
    if (currentUser.role !== "DRR Academic Researcher") { alert("Unauthorized: Only DRR Researchers can approve and publish nodes."); return; }
    const updatedSub = { ...sub, expertStatus: "Validated", scientificValidation: updatedValidation || sub.scientificValidation, expertName: `${currentUser.name} & SSEAYP Advisory Panel`, coordinates: { x: 38 + Math.floor(Math.random() * 10), y: 50 + Math.floor(Math.random() * 12) } };
    setKnowledgeList(prev => [updatedSub, ...prev]);
    setPendingSubmissions(prev => prev.filter(p => p.id !== sub.id));
    setTargetInterviews(p => p + 1);
    setTargetVolunteers(p => p + 1);
    setSelectedNode(updatedSub);
    alert(`Knowledge validated and published by ${currentUser.name}!`);
    setActiveTab('map');
  };

  // Profile
  const handleAvatarUpload = e => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    setAvatarUploadError("");
    setProfileSavedMsg("");
    if (!file.type.startsWith("image/")) { setAvatarUploadError("Please choose a valid image file."); return; }
    if (file.size > 3 * 1024 * 1024) { setAvatarUploadError("Maximum image size is 3MB."); return; }
    const reader = new FileReader();
    reader.onload = ev => setCustomAvatar(ev.target.result);
    reader.onerror = () => setAvatarUploadError("Could not load image, please try again.");
    reader.readAsDataURL(file);
  };

  const handleSaveProfile = async () => {
    setIsSavingProfile(true);
    setProfileSavedMsg("");
    try {
      if (customAvatar) {
        await window.storage.set(`avatar:${currentUser.username}`, customAvatar, false);
        setSavedAvatars(p => ({ ...p, [currentUser.username]: customAvatar }));
        setCustomAvatar(null);
      }
      await window.storage.set(`bio:${currentUser.username}`, bioDraft, false);
      setCurrentUser(prev => ({ ...prev, bio: bioDraft }));
      setProfileSavedMsg("Profile saved successfully.");
    } catch { setProfileSavedMsg("Could not save — please try again."); }
    finally { setIsSavingProfile(false); }
  };

  const handleDeleteSavedAvatar = async () => {
    try { await window.storage.delete(`avatar:${currentUser.username}`, false); } catch {}
    setSavedAvatars(p => { const n = { ...p }; delete n[currentUser.username]; return n; });
    setProfileSavedMsg("Profile picture removed.");
  };

  const getDisplayAvatarFor = u => (customAvatar && u.username === currentUser.username) ? customAvatar : (savedAvatars[u.username] || null);

  const handleLogin = () => {
    setAuthError("");
    const match = Object.values(mockUsers).find(u => u.email.toLowerCase() === loginEmail.trim().toLowerCase());
    if (!match) { setAuthError("No account found with this email. Try: tranght.8924@gmail.com or hoang.nm@vast.vn"); return; }
    setCurrentUser(match); setIsAuthenticated(true);
  };

  const handleRegister = () => {
    setAuthError("");
    if (!registerName.trim() || !registerEmail.trim()) { setAuthError("Please fill in all required fields."); return; }
    const newUser = { username: registerEmail.split("@")[0], name: registerName.trim(), role: registerRole, gender: registerGender, email: registerEmail.trim(), phone: "Not provided yet", bio: "New member of the KIZUNA-AI community.", country: registerCountry };
    setCurrentUser(newUser); setIsAuthenticated(true);
  };

  const handleLogout = () => { setIsAuthenticated(false); setLoginEmail(''); setAuthError(''); setCustomAvatar(null); };

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen bg-slate-900 text-slate-100 flex items-center justify-center p-4 font-sans relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl -mr-20 -mt-20" />
        <div className="absolute bottom-0 left-0 w-80 h-80 bg-amber-500/5 rounded-full blur-3xl -ml-20 -mb-20" />
        <div className="relative z-10 w-full max-w-4xl grid grid-cols-1 lg:grid-cols-2 bg-slate-950 border border-slate-800 rounded-3xl overflow-hidden shadow-2xl">
          <div className="bg-gradient-to-br from-teal-950 via-slate-900 to-slate-950 p-8 flex flex-col justify-between border-r border-slate-800">
            <div>
              <div className="flex items-center gap-3 mb-8">
                <div className="bg-gradient-to-r from-teal-500 to-emerald-500 p-2 rounded-xl shadow-lg shadow-teal-500/20">
                  <svg className="w-6 h-6 text-slate-950" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /></svg>
                </div>
                <h1 className="text-xl font-extrabold tracking-wide bg-gradient-to-r from-teal-400 via-emerald-400 to-amber-300 bg-clip-text text-transparent">KIZUNA-AI</h1>
              </div>
              <h2 className="text-2xl font-extrabold text-white leading-tight">Join the community preserving indigenous knowledge</h2>
              <p className="text-sm text-slate-400 mt-3 leading-relaxed">Interview elders, contribute folk stories, or join the scientific review panel — across ASEAN & Japan.</p>
            </div>
            <div className="space-y-2 mt-8">
              {["AI-powered archiving and multilingual translation", "Scientific validation by DRR experts", "Regional knowledge map across ASEAN & Japan", "Open to all stakeholders — youth to policymakers"].map(f => (
                <div key={f} className="flex items-center gap-2 text-xs text-slate-400"><span className="text-teal-400">✓</span>{f}</div>
              ))}
            </div>
          </div>

          <div className="p-8 flex flex-col justify-center overflow-y-auto max-h-screen">
            <div className="flex bg-slate-900 border border-slate-800 p-1 rounded-xl mb-5">
              <button onClick={() => { setAuthMode('login'); setAuthError(""); }} className={`flex-1 py-2 rounded-lg text-xs font-semibold transition-all ${authMode === 'login' ? 'bg-teal-600 text-white' : 'text-slate-400 hover:text-white'}`}>Sign In</button>
              <button onClick={() => { setAuthMode('register'); setAuthError(""); }} className={`flex-1 py-2 rounded-lg text-xs font-semibold transition-all ${authMode === 'register' ? 'bg-teal-600 text-white' : 'text-slate-400 hover:text-white'}`}>Register</button>
            </div>
            {authError && <div className="bg-red-950/40 border border-red-500/30 text-red-200 text-xs p-3 rounded-xl mb-4">{authError}</div>}

            {authMode === 'login' && (
              <div className="space-y-4">
                <div className="space-y-2">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">Quick demo sign-in</span>
                  <div className="grid grid-cols-2 gap-2">
                    {[mockUsers.volunteer, mockUsers.expert].map(u => (
                      <button key={u.username} onClick={() => { setCurrentUser(u); setIsAuthenticated(true); }} className="flex items-center gap-2 bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-teal-500/50 rounded-xl p-2.5 text-left transition-all">
                        <AvatarIcon gender={u.gender} className="w-8 h-8 rounded-full bg-slate-800" />
                        <div><p className="text-[11px] font-bold text-white leading-tight">{u.name.split(' ').slice(-1)[0]}</p><p className="text-[9px] text-teal-400">{u.role.split('/')[0].trim()}</p></div>
                      </button>
                    ))}
                  </div>
                  <div className="flex items-center gap-2 pt-1"><div className="h-px bg-slate-800 flex-1" /><span className="text-[9px] text-slate-600">or email</span><div className="h-px bg-slate-800 flex-1" /></div>
                </div>
                <div>
                  <label className="text-[10px] font-bold text-slate-500 block mb-1">EMAIL</label>
                  <input type="email" value={loginEmail} onChange={e => setLoginEmail(e.target.value)} placeholder="you@email.com" className="bg-slate-900 border border-slate-800 p-2.5 rounded-xl w-full text-sm focus:outline-none focus:border-teal-500 text-white placeholder:text-slate-600" />
                </div>
                <button onClick={handleLogin} className="w-full bg-gradient-to-r from-teal-500 to-emerald-500 text-slate-950 font-bold py-3 rounded-xl text-sm">Sign in to KIZUNA-AI</button>
                <p className="text-[10px] text-slate-500 text-center">Demo: tranght.8924@gmail.com · hoang.nm@vast.vn</p>
              </div>
            )}

            {authMode === 'register' && (
              <div className="space-y-3">
                <div><label className="text-[10px] font-bold text-slate-500 block mb-1">FULL NAME *</label><input type="text" value={registerName} onChange={e => setRegisterName(e.target.value)} placeholder="Your full name" className="bg-slate-900 border border-slate-800 p-2.5 rounded-xl w-full text-sm focus:outline-none focus:border-teal-500 text-white placeholder:text-slate-600" /></div>
                <div><label className="text-[10px] font-bold text-slate-500 block mb-1">EMAIL *</label><input type="email" value={registerEmail} onChange={e => setRegisterEmail(e.target.value)} placeholder="you@email.com" className="bg-slate-900 border border-slate-800 p-2.5 rounded-xl w-full text-sm focus:outline-none focus:border-teal-500 text-white placeholder:text-slate-600" /></div>
                <div className="grid grid-cols-2 gap-3">
                  <div><label className="text-[10px] font-bold text-slate-500 block mb-1">COUNTRY</label><input type="text" value={registerCountry} onChange={e => setRegisterCountry(e.target.value)} className="bg-slate-900 border border-slate-800 p-2.5 rounded-xl w-full text-sm focus:outline-none focus:border-teal-500 text-white" /></div>
                  <div>
                    <label className="text-[10px] font-bold text-slate-500 block mb-1">AVATAR STYLE</label>
                    <div className="flex gap-2">
                      {['male', 'female'].map(g => (
                        <button key={g} onClick={() => setRegisterGender(g)} className={`flex-1 flex items-center justify-center gap-1 p-2 rounded-xl border text-[10px] font-semibold transition-all ${registerGender === g ? 'border-teal-500 bg-teal-950/40 text-white' : 'border-slate-800 bg-slate-900 text-slate-400'}`}>
                          <AvatarIcon gender={g} className="w-5 h-5 rounded-full" />{g.charAt(0).toUpperCase() + g.slice(1)}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
                <div>
                  <label className="text-[10px] font-bold text-slate-500 block mb-1">YOUR STAKEHOLDER ROLE</label>
                  <div className="space-y-1 max-h-44 overflow-y-auto pr-1">
                    {ALL_ROLES.map(r => (
                      <button key={r.value} onClick={() => setRegisterRole(r.value)} className={`w-full text-left p-2.5 rounded-xl border text-xs transition-all ${registerRole === r.value ? 'border-teal-500 bg-teal-950/30' : 'border-slate-800 bg-slate-900 hover:border-slate-700'}`}>
                        <span className="font-semibold text-white block">{r.label}</span>
                        <span className="text-slate-500 text-[10px]">{r.desc}</span>
                      </button>
                    ))}
                  </div>
                </div>
                <button onClick={handleRegister} className="w-full bg-gradient-to-r from-teal-500 to-emerald-500 text-slate-950 font-bold py-3 rounded-xl text-sm mt-1">Create Account & Join</button>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }

  const headerAvatar = getDisplayAvatarFor(currentUser);

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex flex-col font-sans">
      <header className="bg-slate-950/80 backdrop-blur border-b border-teal-500/20 sticky top-0 z-50 px-6 py-4 flex flex-col md:flex-row justify-between items-center gap-4">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-r from-teal-500 to-emerald-500 p-2 rounded-xl shadow-lg shadow-teal-500/20">
            <svg className="w-6 h-6 text-slate-950" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /></svg>
          </div>
          <div>
            <h1 className="text-xl font-extrabold tracking-wide bg-gradient-to-r from-teal-400 via-emerald-400 to-amber-300 bg-clip-text text-transparent">KIZUNA-AI</h1>
            <p className="text-xs text-slate-400 font-medium">Connecting Generations for Community Resilience</p>
          </div>
        </div>
        <nav className="flex bg-slate-900 border border-slate-800 p-1 rounded-xl flex-wrap justify-center">
          {[['dashboard','Dashboard'],['map','Knowledge Map'],['ai-engine','KIZUNA-AI Engine'],['expert-review','Review Board'],['expedition','SSEAYP Hub'],['profile-center','Profile & Role']].map(([tab, label]) => (
            <button key={tab} onClick={() => setActiveTab(tab)} className={`px-3 py-2 rounded-lg text-xs font-semibold transition-all relative ${activeTab === tab ? (tab === 'profile-center' ? 'bg-indigo-600 text-white' : 'bg-teal-600 text-white') : (tab === 'profile-center' ? 'border border-dashed border-indigo-500/30 text-indigo-400 hover:text-white' : 'text-slate-400 hover:text-white')}`}>
              {label}
              {tab === 'expert-review' && pendingSubmissions.length > 0 && <span className="absolute -top-1.5 -right-1.5 bg-red-500 text-white font-bold text-[10px] w-4 h-4 flex items-center justify-center rounded-full border border-slate-900">{pendingSubmissions.length}</span>}
            </button>
          ))}
        </nav>
        <div className="flex items-center gap-3 bg-slate-900 px-3 py-1.5 rounded-xl border border-slate-800">
          {headerAvatar ? <img src={headerAvatar} alt="avatar" className="w-8 h-8 rounded-full object-cover border border-teal-500/40 bg-slate-800" /> : <AvatarIcon gender={currentUser.gender} className="w-8 h-8 rounded-full border border-teal-500/40 bg-slate-800" />}
          <div className="text-left hidden lg:block">
            <p className="text-[11px] font-bold text-white leading-tight">{currentUser.name}</p>
            <select value={Object.keys(mockUsers).find(k => mockUsers[k].role === currentUser.role) || ""} onChange={e => e.target.value && setCurrentUser(mockUsers[e.target.value])} className="bg-transparent text-[10px] text-teal-400 focus:outline-none cursor-pointer font-medium">
              <option value="" disabled hidden>Switch role</option>
              <option value="volunteer" className="bg-slate-950 text-slate-100">Volunteer Mode</option>
              <option value="expert" className="bg-slate-950 text-slate-100">Expert Mode</option>
              <option value="interviewee" className="bg-slate-950 text-slate-100">Elder Mode</option>
            </select>
          </div>
          <button onClick={handleLogout} className="text-[10px] font-bold text-slate-500 hover:text-red-400 border-l border-slate-800 pl-3 ml-1">Sign out</button>
        </div>
      </header>

      <main className="flex-1 max-w-7xl w-full mx-auto p-4 md:p-6 overflow-x-hidden">

        {/* ── DASHBOARD ── */}
        {activeTab === 'dashboard' && (
          <div className="space-y-6">
            <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-teal-950 via-slate-900 to-slate-950 border border-teal-500/30 p-6 md:p-8">
              <div className="absolute top-0 right-0 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl -mr-20 -mt-20" />
              <div className="relative z-10 max-w-3xl space-y-4">
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-teal-900/50 text-teal-300 border border-teal-500/20">SSEAYP Social Initiative</span>
                <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight text-white">Preserving Indigenous Wisdom through Heart-to-Heart AI Connections</h2>
                <p className="text-slate-300 text-sm md:text-base leading-relaxed">As climate change accelerates, a silent crisis unfolds — generational knowledge is disappearing. <strong className="text-teal-300">KIZUNA-AI</strong> enables youth volunteers to collect local oral histories, then deploys AI to transcribe, translate, structure, and scientifically validate vital ecological survival markers.</p>
                <div className="flex flex-wrap gap-4 pt-2">
                  <button onClick={() => setActiveTab('ai-engine')} className="bg-gradient-to-r from-teal-500 to-emerald-500 text-slate-950 font-bold px-6 py-3 rounded-xl shadow-lg text-sm flex items-center gap-2">Launch Live AI Pipeline Demo <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7"/></svg></button>
                  <button onClick={() => setActiveTab('map')} className="bg-slate-800 hover:bg-slate-700 text-white border border-slate-700 font-semibold px-6 py-3 rounded-xl text-sm">Browse Knowledge Map</button>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
              {[[targetInterviews,300,"Phase 1 Interviews","teal"],[targetVolunteers,150,"Youth Curators Trained","emerald"]].map(([val,max,label,color]) => (
                <div key={label} className="bg-slate-950 border border-slate-800 p-5 rounded-2xl">
                  <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">{label}</p>
                  <div className="flex items-baseline gap-2 mt-2"><span className="text-3xl font-extrabold text-white">{val}</span><span className="text-xs text-slate-500">of {max}</span></div>
                  <div className="w-full bg-slate-800 h-2 rounded-full mt-4 overflow-hidden"><div className={`bg-${color}-500 h-full rounded-full`} style={{width:`${(val/max)*100}%`}} /></div>
                </div>
              ))}
              <div className="bg-slate-950 border border-slate-800 p-5 rounded-2xl"><p className="text-xs text-slate-400 font-medium uppercase tracking-wider">Pilot Countries</p><span className="text-2xl font-extrabold text-amber-400 mt-2 block">2 → 5</span><span className="text-xs text-slate-400 mt-2 block">Vietnam & Japan (Expanding to PHL, IDN, THA)</span></div>
              <div className="bg-slate-950 border border-slate-800 p-5 rounded-2xl"><p className="text-xs text-slate-400 font-medium uppercase tracking-wider">UN/SSEAYP Themes</p><span className="text-2xl font-extrabold text-teal-400 mt-2 block">4 Key Themes</span><span className="text-xs text-slate-400 mt-2 block">Climate · DRR · Education · AI Technology</span></div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              {[["1","Youth Interview Fieldwork","Youth volunteers conduct audio interviews with elderly sea-readers, farmers, and village veterans."],["2","AI Curation Hub","Generative AI structures dialect, transcribes, translates to English/Japanese, and uncovers distinct warnings."],["3","Scientific Validation","DRR researchers assess the scientific basis of indicators, ensuring credibility."],["4","Regional Sharing Network","Cross-border insights are pushed to community maps, climate centers, and educational textbooks."]].map(([n,title,desc]) => (
                <div key={n} className="bg-slate-900 border border-slate-800/60 p-5 rounded-2xl">
                  <div className="bg-teal-500/10 text-teal-400 w-10 h-10 rounded-xl flex items-center justify-center font-bold mb-3 border border-teal-500/20">{n}</div>
                  <h4 className="font-bold text-white mb-1">{title}</h4>
                  <p className="text-xs text-slate-400 leading-relaxed">{desc}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── MAP ── */}
        {activeTab === 'map' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-7 bg-slate-950 border border-slate-800 rounded-3xl p-6 flex flex-col relative min-h-[450px]">
              <div className="mb-4">
                <h3 className="text-lg font-bold text-white">KIZUNA Regional Knowledge Map</h3>
                <p className="text-xs text-slate-400">Click nodes to view local storm & climate observations. Scroll to zoom, drag to pan.</p>
              </div>
              <div className={`flex-1 bg-slate-900/50 rounded-2xl relative border border-slate-800 flex items-center justify-center p-2 overflow-hidden ${mapZoom > 1 ? (isDraggingMap ? 'cursor-grabbing' : 'cursor-grab') : ''}`} onWheel={handleWheelZoom} onMouseDown={handleMapMouseDown} onMouseMove={handleMapMouseMove} onMouseUp={handleMapMouseUp} onMouseLeave={handleMapMouseUp}>
                <div style={{ transform: `translate(${mapPan.x}px,${mapPan.y}px) scale(${mapZoom})`, transition: isDraggingMap ? 'none' : 'transform 0.15s ease-out', width: '100%', maxWidth: '550px' }}>
                  <svg className="w-full aspect-[4/3] text-slate-800 select-none" viewBox="0 0 100 100" fill="currentColor">
                    <defs><pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M 10 0 L 0 0 0 10" fill="none" stroke="rgba(20,184,166,0.05)" strokeWidth="0.5"/></pattern></defs>
                    <rect width="100" height="100" fill="url(#grid)" />
                    <text x="36" y="42" fontSize="3" className="fill-slate-500 font-bold tracking-wider">HANOI</text>
                    <text x="76" y="14" fontSize="3" className="fill-slate-500 font-bold tracking-wider">TOKYO</text>
                    <text x="43" y="66" fontSize="3" className="fill-slate-500 font-bold tracking-wider">MANILA</text>
                    {knowledgeList.map(node => {
                      const isSel = selectedNode.id === node.id;
                      return (
                        <g key={node.id} className="cursor-pointer group" onClick={() => setSelectedNode(node)}>
                          <circle cx={node.coordinates.x} cy={node.coordinates.y} r={isSel ? "5" : "3.5"} className={`fill-none stroke-teal-400/40 ${isSel ? "animate-pulse stroke-2" : "group-hover:stroke-teal-500/30"}`} />
                          <circle cx={node.coordinates.x} cy={node.coordinates.y} r={isSel ? "2" : "1.5"} className={`${isSel ? "fill-teal-400" : "fill-teal-600 group-hover:fill-teal-400"} transition-all`} />
                          <rect x={node.coordinates.x-12} y={node.coordinates.y-9} width="24" height="4.5" rx="1" className={`${isSel ? "fill-teal-900/90 stroke-teal-400" : "fill-slate-950/80 stroke-slate-800"} stroke-[0.35]`} />
                          <text x={node.coordinates.x} y={node.coordinates.y-6} textAnchor="middle" fontSize="2" className="fill-white font-bold">{node.country}</text>
                        </g>
                      );
                    })}
                  </svg>
                </div>
                <div className="absolute top-4 right-4 bg-slate-950/90 border border-slate-800 rounded-xl flex flex-col z-10 overflow-hidden">
                  <button onClick={handleZoomIn} disabled={mapZoom >= 4} className="w-8 h-8 flex items-center justify-center text-slate-300 hover:bg-slate-800 hover:text-teal-400 disabled:opacity-30 text-base font-bold border-b border-slate-800">+</button>
                  <button onClick={handleZoomOut} disabled={mapZoom <= 1} className="w-8 h-8 flex items-center justify-center text-slate-300 hover:bg-slate-800 hover:text-teal-400 disabled:opacity-30 text-base font-bold border-b border-slate-800">−</button>
                  <button onClick={handleResetView} className="w-8 h-8 flex items-center justify-center text-slate-400 hover:bg-slate-800 hover:text-teal-400 text-[9px] font-bold">1:1</button>
                </div>
              </div>
            </div>
            <div className="lg:col-span-5">
              {selectedNode && (
                <div className="bg-slate-950 border border-slate-800 rounded-3xl p-6 space-y-4">
                  <div className="flex justify-between items-start gap-2">
                    <div className="space-y-1">
                      <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-teal-950/80 text-teal-300 border border-teal-500/30">{selectedNode.theme}</span>
                      <h4 className="text-lg font-bold text-white leading-tight">{selectedNode.title}</h4>
                      <p className="text-xs text-slate-400">{selectedNode.location}</p>
                    </div>
                    <span className="bg-emerald-950/80 border border-emerald-500/30 text-emerald-400 font-bold text-[10px] px-2 py-1 rounded-lg shrink-0">✓ Validated</span>
                  </div>
                  <div className="bg-slate-900/50 border border-slate-800/80 p-4 rounded-2xl relative">
                    <span className="absolute -top-2.5 left-4 bg-slate-950 px-2 text-[10px] font-bold text-slate-500 uppercase tracking-wider">Original Recording</span>
                    <blockquote className="text-sm italic text-slate-300 leading-relaxed pt-1">"{selectedNode.originalText}"</blockquote>
                    <div className="mt-3 flex justify-between items-center text-xs border-t border-slate-800/80 pt-2">
                      <span className="text-slate-400">Keeper: <strong className="text-white">{selectedNode.elderName}</strong> (Age {selectedNode.elderAge})</span>
                      <span className="text-slate-500 text-[10px]">By {selectedNode.curatedBy}</span>
                    </div>
                  </div>
                  <div className="grid grid-cols-1 gap-2 text-xs">
                    {[["English Edition", selectedNode.englishTranslation], ["Japanese Edition", selectedNode.japaneseTranslation]].map(([label, text]) => (
                      <div key={label} className="bg-slate-900/40 p-2.5 rounded-xl border border-slate-800/50">
                        <span className="font-bold text-slate-500 uppercase text-[9px] block">{label}</span>
                        <p className="text-slate-300 mt-0.5">{text}</p>
                      </div>
                    ))}
                  </div>
                  <div className="space-y-1.5">
                    <span className="text-xs font-bold text-amber-400">Warning Triggers</span>
                    <ul className="space-y-1">{selectedNode.warningSigns.map((s, i) => (<li key={i} className="bg-amber-950/20 text-amber-200 border border-amber-500/10 text-xs p-2 rounded-lg flex items-start gap-2"><span className="text-amber-500 mt-0.5">●</span><span>{s}</span></li>))}</ul>
                  </div>
                  <div className="bg-gradient-to-br from-indigo-950/40 to-slate-900/40 border border-indigo-500/20 p-4 rounded-2xl">
                    <span className="text-xs font-bold text-indigo-400 block mb-1">Expert Scientific Validation</span>
                    <p className="text-xs text-indigo-200/90 leading-relaxed">{selectedNode.scientificValidation}</p>
                    {selectedNode.expertName && <p className="mt-2 text-[10px] text-indigo-400/75">Reviewed by: {selectedNode.expertName}</p>}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* ── AI ENGINE ── */}
        {activeTab === 'ai-engine' && (
          <div className="space-y-6">
            {currentUser.role !== "Youth Curator / Field Volunteer" && (
              <div className="bg-amber-950/40 border border-amber-500/30 p-4 rounded-2xl text-amber-200 text-xs">
                <strong>RBAC Notice:</strong> Only <strong>Youth Curators / Field Volunteers</strong> can submit curation logs. You can explore, but pipeline submissions will be attributed to your current role: <strong>{currentUser.role}</strong>.
              </div>
            )}

            <div className="bg-slate-950 border border-slate-800 rounded-3xl p-6 md:p-8">
              <h3 className="text-2xl font-extrabold text-white mb-1">KIZUNA-AI Processing Pipeline</h3>
              <p className="text-sm text-slate-400 mb-6">Three sequential stages: Upload an audio interview → AI transcribes the dialect → AI structures & validates the knowledge.</p>

              {/* Stage indicator */}
              <div className="flex items-center gap-2 mb-8 flex-wrap">
                {[["Upload Audio","upload"],["Transcribe","transcribed"],["Process & Validate","done"]].map(([label, stage], idx) => {
                  const stageOrder = ['upload','transcribing','transcribed','processing','done'];
                  const current = stageOrder.indexOf(aiStage);
                  const target = stageOrder.indexOf(stage);
                  const done = current > target || aiStage === stage;
                  const active = aiStage === stage || (stage === 'upload' && (aiStage === 'upload' || aiStage === 'transcribing')) || (stage === 'transcribed' && aiStage === 'transcribed') || (stage === 'done' && (aiStage === 'processing' || aiStage === 'done'));
                  return (
                    <React.Fragment key={stage}>
                      <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-bold border transition-all ${active ? 'bg-teal-900/50 border-teal-500 text-teal-300' : done ? 'bg-emerald-950/30 border-emerald-500/30 text-emerald-400' : 'bg-slate-900 border-slate-800 text-slate-500'}`}>
                        <span className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-extrabold ${active ? 'bg-teal-500 text-slate-950' : done ? 'bg-emerald-500 text-slate-950' : 'bg-slate-800 text-slate-500'}`}>{done && !active ? '✓' : idx+1}</span>
                        {label}
                      </div>
                      {idx < 2 && <div className="h-px w-6 bg-slate-700 flex-shrink-0" />}
                    </React.Fragment>
                  );
                })}
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

                {/* STEP 1 — Upload */}
                <div className={`bg-slate-900 border rounded-2xl p-5 space-y-4 transition-all ${aiStage !== 'upload' && aiStage !== 'transcribing' ? 'border-emerald-500/30 opacity-70' : 'border-teal-500/40'}`}>
                  <div className="flex items-center gap-2 pb-2 border-b border-slate-800">
                    <span className="w-6 h-6 rounded-full bg-teal-500 text-slate-950 flex items-center justify-center text-[11px] font-extrabold">1</span>
                    <span className="text-sm font-bold text-white">Upload Audio Interview</span>
                  </div>
                  <div className="text-xs space-y-3">
                    <div className="grid grid-cols-3 gap-2">
                      <div><label className="text-[10px] font-bold text-slate-500 block mb-1">ELDER NAME</label><input type="text" value={customAuthor} onChange={e => setCustomAuthor(e.target.value)} className="bg-slate-950 border border-slate-800 px-2 py-1.5 rounded-lg text-xs w-full focus:outline-none focus:border-teal-500 text-white" /></div>
                      <div><label className="text-[10px] font-bold text-slate-500 block mb-1">AGE</label><input type="number" value={customAge} onChange={e => setCustomAge(e.target.value)} className="bg-slate-950 border border-slate-800 px-2 py-1.5 rounded-lg text-xs w-full focus:outline-none focus:border-teal-500 text-white" /></div>
                      <div><label className="text-[10px] font-bold text-slate-500 block mb-1">LOCATION</label><input type="text" value={customLoc} onChange={e => setCustomLoc(e.target.value)} className="bg-slate-950 border border-slate-800 px-2 py-1.5 rounded-lg text-xs w-full focus:outline-none focus:border-teal-500 text-white" /></div>
                    </div>
                    <div>
                      <label className="text-[10px] font-bold text-slate-500 block mb-2">AUDIO FILE (MP3, WAV, OGG, M4A)</label>
                      <input ref={audioInputRef} type="file" accept="audio/*,video/mp4" onChange={handleAudioUpload} className="hidden" />
                      <div onClick={() => audioInputRef.current && audioInputRef.current.click()} className={`border-2 border-dashed rounded-xl p-6 flex flex-col items-center justify-center gap-2 cursor-pointer transition-all ${uploadedFile ? 'border-teal-500/60 bg-teal-950/20' : 'border-slate-700 hover:border-teal-500/40 bg-slate-950/50'}`}>
                        <svg className={`w-8 h-8 ${uploadedFile ? 'text-teal-400' : 'text-slate-600'}`} fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 18.75a6 6 0 006-6v-1.5m-6 7.5a6 6 0 01-6-6v-1.5m6 7.5v3.75m-3.75 0h7.5M12 15.75a3 3 0 01-3-3V4.5a3 3 0 116 0v8.25a3 3 0 01-3 3z" /></svg>
                        {uploadedFile ? (
                          <div className="text-center"><p className="text-teal-300 font-semibold text-[11px]">{uploadedFile.name}</p><p className="text-slate-500 text-[10px]">{(uploadedFile.size/1024).toFixed(1)} KB · Click to replace</p></div>
                        ) : (
                          <div className="text-center"><p className="text-slate-400 text-[11px] font-medium">Click or drop audio file here</p><p className="text-slate-600 text-[10px] mt-0.5">MP3 · WAV · OGG · M4A · MP4</p></div>
                        )}
                      </div>
                    </div>
                    <div>
                      <label className="text-[10px] font-bold text-slate-500 block mb-1">OR CHOOSE A DEMO RECORDING</label>
                      <div className="space-y-1">
                        {draftPresets.map(p => (
                          <button key={p.id} onClick={() => { setCustomAuthor(p.author); setCustomAge(p.age.toString()); setCustomLoc(p.location); setUploadedFile({ name: `demo_${p.author.replace(/ /g,'_')}.mp3`, size: 1024*Math.floor(Math.random()*400+200) }); setAiStage('upload'); setAiResult(null); setTranscriptText(''); }} className="w-full text-left bg-slate-950 hover:bg-slate-900 border border-slate-800 hover:border-teal-500/30 rounded-lg p-2 transition-all">
                            <span className="text-[11px] font-semibold text-white block">{p.author}</span>
                            <span className="text-[10px] text-slate-500">{p.dialect} · {p.location}</span>
                          </button>
                        ))}
                      </div>
                    </div>
                    <button onClick={handleStartTranscribe} disabled={!uploadedFile || aiStage === 'transcribing'} className="w-full bg-teal-600 hover:bg-teal-500 disabled:opacity-40 text-white font-bold py-2.5 rounded-xl text-xs flex items-center justify-center gap-2 transition-all">
                      {aiStage === 'transcribing' ? (<><svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>Transcribing...</>) : 'Start Transcription →'}
                    </button>
                  </div>
                </div>

                {/* STEP 2 — Transcribe */}
                <div className={`bg-slate-900 border rounded-2xl p-5 space-y-3 transition-all ${aiStage === 'upload' ? 'border-slate-800 opacity-50' : aiStage === 'transcribing' || aiStage === 'transcribed' ? 'border-teal-500/40' : 'border-emerald-500/30 opacity-70'}`}>
                  <div className="flex items-center gap-2 pb-2 border-b border-slate-800">
                    <span className="w-6 h-6 rounded-full bg-teal-500 text-slate-950 flex items-center justify-center text-[11px] font-extrabold">2</span>
                    <span className="text-sm font-bold text-white">AI Transcription</span>
                  </div>
                  {(aiStage === 'transcribing' || aiStage === 'transcribed' || aiStage === 'processing' || aiStage === 'done') ? (
                    <div className="space-y-3 text-xs">
                      <div className="flex justify-between items-center">
                        <span className="text-[10px] text-slate-500 font-bold uppercase">Transcription Progress</span>
                        <span className={`text-[10px] font-bold ${transcriptProgress === 100 ? 'text-emerald-400' : 'text-amber-400 animate-pulse'}`}>{transcriptProgress}%</span>
                      </div>
                      <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden"><div className="bg-teal-500 h-full rounded-full transition-all duration-150" style={{width:`${transcriptProgress}%`}} /></div>
                      <div className="bg-slate-950 border border-slate-800 rounded-xl p-3 min-h-[120px] relative">
                        <span className="text-[9px] font-bold text-slate-600 uppercase block mb-1">Raw Transcript Output</span>
                        <p className="text-slate-300 leading-relaxed text-[11px]">{transcriptText || "Waiting for audio analysis..."}<span className={`inline-block w-1.5 h-3.5 bg-teal-400 ml-0.5 align-middle ${aiStage === 'transcribing' ? 'animate-pulse' : 'hidden'}`} /></p>
                      </div>
                      {transcriptProgress === 100 && (
                        <div className="flex gap-1.5 flex-wrap">
                          <span className="bg-teal-950/40 text-teal-300 border border-teal-500/20 px-2 py-0.5 rounded-md text-[10px] font-semibold">✓ Dialect detected</span>
                          <span className="bg-teal-950/40 text-teal-300 border border-teal-500/20 px-2 py-0.5 rounded-md text-[10px] font-semibold">✓ 97.4% confidence</span>
                          <span className="bg-teal-950/40 text-teal-300 border border-teal-500/20 px-2 py-0.5 rounded-md text-[10px] font-semibold">✓ Ready to process</span>
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-40 text-center gap-2">
                      <svg className="w-10 h-10 text-slate-700" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M3.75 9h16.5m-16.5 6.75h16.5" /></svg>
                      <p className="text-xs text-slate-600">Upload an audio file first,<br/>then start transcription.</p>
                    </div>
                  )}
                </div>

                {/* STEP 3 — Process */}
                <div className={`bg-slate-900 border rounded-2xl p-5 space-y-3 transition-all ${aiStage !== 'transcribed' && aiStage !== 'processing' && aiStage !== 'done' ? 'border-slate-800 opacity-50' : 'border-teal-500/40'}`}>
                  <div className="flex items-center gap-2 pb-2 border-b border-slate-800">
                    <span className="w-6 h-6 rounded-full bg-teal-500 text-slate-950 flex items-center justify-center text-[11px] font-extrabold">3</span>
                    <span className="text-sm font-bold text-white">AI Knowledge Extraction</span>
                  </div>
                  {aiStage === 'processing' && (
                    <div className="space-y-2 text-xs">
                      {processingSteps.map((step, idx) => (
                        <div key={idx} className={`p-2 rounded-xl border flex items-center gap-2 text-[11px] transition-all ${idx < processingStep ? 'bg-emerald-950/20 border-emerald-500/20 text-emerald-400' : idx === processingStep ? 'bg-amber-950/20 border-amber-500/30 text-amber-200 animate-pulse' : 'bg-slate-950 border-slate-800 text-slate-600'}`}>
                          <span>{idx < processingStep ? '✓' : idx === processingStep ? '⚡' : '○'}</span><span>{step}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  {(aiStage === 'transcribed' || (aiStage !== 'processing' && !aiResult)) && aiStage !== 'processing' && !aiResult && (
                    <div className="flex flex-col items-center justify-center gap-3 py-4 text-center">
                      <svg className="w-10 h-10 text-slate-700" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" /></svg>
                      {aiStage === 'transcribed' ? <p className="text-xs text-slate-400">Transcription ready!<br/>Click below to extract knowledge.</p> : <p className="text-xs text-slate-600">Complete transcription first.</p>}
                    </div>
                  )}
                  {aiResult && aiStage === 'done' && (
                    <div className="space-y-3 text-xs">
                      <div><span className="text-[10px] font-bold text-teal-400 block">EXTRACTED TITLE</span><span className="text-sm font-bold text-white">{aiResult.title}</span><span className="text-[10px] text-slate-400 block">{aiResult.theme} · by {aiResult.curatedBy}</span></div>
                      <div className="grid grid-cols-1 gap-2">
                        <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800"><span className="text-[9px] font-bold text-slate-500 block uppercase">English</span><p className="text-slate-300 mt-0.5 text-[11px]">{aiResult.englishTranslation}</p></div>
                        <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800"><span className="text-[9px] font-bold text-slate-500 block uppercase">Japanese</span><p className="text-slate-300 mt-0.5 text-[11px]">{aiResult.japaneseTranslation}</p></div>
                      </div>
                      <div><span className="text-[10px] font-bold text-amber-400 block mb-1">Warning Triggers</span><div className="flex flex-wrap gap-1">{aiResult.warningSigns.map((s,i)=>(<span key={i} className="bg-amber-950/30 text-amber-200 border border-amber-500/10 text-[10px] px-2 py-0.5 rounded-md">{s}</span>))}</div></div>
                      <div className="bg-indigo-950/10 border border-indigo-500/20 p-2.5 rounded-xl"><span className="text-[10px] font-bold text-indigo-400 block">Scientific Hypothesis</span><p className="text-indigo-200 text-[11px] leading-relaxed mt-0.5">{aiResult.scientificValidation}</p></div>
                    </div>
                  )}
                  <div className="flex gap-2 pt-1">
                    {aiStage === 'transcribed' && (
                      <button onClick={handleRunProcess} className="flex-1 bg-gradient-to-r from-teal-500 to-emerald-500 text-slate-950 font-bold py-2.5 rounded-xl text-xs">Run AI Extraction →</button>
                    )}
                    {aiResult && aiStage === 'done' && (
                      <>
                        <button onClick={() => { setAiResult(null); setAiStage('transcribed'); }} className="px-3 py-2 bg-slate-950 border border-slate-800 text-slate-400 hover:text-white rounded-xl text-xs">Discard</button>
                        <button onClick={submitToExpertQueue} className="flex-1 bg-teal-600 hover:bg-teal-500 text-white font-bold py-2 rounded-xl text-xs">Send to Review Board →</button>
                      </>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ── EXPERT REVIEW ── */}
        {activeTab === 'expert-review' && (
          <div className="space-y-6">
            {currentUser.role !== "DRR Academic Researcher" && (
              <div className="bg-red-950/40 border border-red-500/30 p-5 rounded-2xl text-red-200 text-xs">
                <strong className="text-sm block mb-1">🔒 Role Lock Active</strong>
                Your current session is <strong>{currentUser.role}</strong>. Only <strong>DRR Academic Researchers</strong> can validate and publish entries. Switch to Expert Mode at the top header.
              </div>
            )}
            <div className="bg-slate-950 border border-slate-800 rounded-3xl p-6">
              <h3 className="text-xl font-extrabold text-white mb-1">Expert Review Board</h3>
              <p className="text-xs text-slate-400 mb-6">Review AI-curated oral history drafts, refine the scientific rationale, and publish validated entries to the knowledge map.</p>
              {pendingSubmissions.length === 0 ? (
                <div className="bg-slate-900/50 p-12 text-center rounded-2xl border border-dashed border-slate-800">
                  <span className="text-3xl">🎉</span>
                  <h4 className="font-bold text-white mt-2">All Clear — No Pending Submissions</h4>
                  <p className="text-xs text-slate-400 mt-1">Use the KIZUNA-AI Engine tab to process audio interviews and submit them here.</p>
                </div>
              ) : (
                <div className="space-y-6">
                  {pendingSubmissions.map(sub => (
                    <div key={sub.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
                      <div className="flex justify-between items-start flex-wrap gap-2 pb-3 border-b border-slate-800">
                        <div>
                          <span className="text-xs font-bold text-amber-400">{sub.theme}</span>
                          <h4 className="text-base font-bold text-white">{sub.title}</h4>
                          <p className="text-xs text-slate-400">{sub.location} · Collected by {sub.curatedBy}</p>
                        </div>
                        <span className="bg-amber-950/50 border border-amber-500/20 text-amber-400 px-3 py-1 rounded-xl font-bold text-[10px]">{sub.expertStatus}</span>
                      </div>
                      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800/80">
                          <span className="text-[10px] text-slate-500 font-bold block uppercase mb-1">Elder's Testimony</span>
                          <blockquote className="text-xs italic text-slate-300 leading-relaxed">"{sub.originalText}"</blockquote>
                          <p className="text-[10px] text-slate-500 mt-2">{sub.elderName} (Age {sub.elderAge})</p>
                        </div>
                        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800/80 space-y-2">
                          <span className="text-[10px] text-slate-500 font-bold block uppercase">AI Translations</span>
                          <div><span className="text-[9px] font-bold text-teal-400 block">English</span><p className="text-[11px] text-slate-300">{sub.englishTranslation}</p></div>
                          <div><span className="text-[9px] font-bold text-teal-400 block">Japanese</span><p className="text-[11px] text-slate-300">{sub.japaneseTranslation}</p></div>
                        </div>
                        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800/80">
                          <span className="text-[10px] text-slate-500 font-bold block uppercase mb-1">Warning Signals</span>
                          <ul className="space-y-1 text-[11px] text-amber-200">{sub.warningSigns.map((s,i)=>(<li key={i} className="flex gap-1.5"><span>•</span><span>{s}</span></li>))}</ul>
                        </div>
                      </div>
                      <div className="bg-slate-950 p-4 rounded-xl border border-slate-800/80 space-y-2">
                        <label className="text-[11px] font-bold text-indigo-400 block">Edit Scientific Validation Summary</label>
                        <textarea rows={3} defaultValue={sub.scientificValidation} id={`val-${sub.id}`} disabled={currentUser.role !== "DRR Academic Researcher"} className="bg-slate-900 border border-slate-800 p-3 rounded-lg text-xs text-slate-200 w-full focus:outline-none focus:border-indigo-500 disabled:opacity-40" />
                      </div>
                      <div className="flex justify-end gap-3 pt-1">
                        <button onClick={() => { const v = document.getElementById(`val-${sub.id}`).value; handleApproveSub(sub, v); }} className={`font-bold text-xs px-5 py-2.5 rounded-xl transition-all text-white ${currentUser.role === "DRR Academic Researcher" ? "bg-emerald-600 hover:bg-emerald-500" : "bg-slate-800 opacity-50 cursor-not-allowed"}`}>
                          {currentUser.role === "DRR Academic Researcher" ? "✓ Validate & Publish to Map" : "🔒 Locked"}
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {/* ── SSEAYP HUB ── */}
        {activeTab === 'expedition' && (
          <div className="space-y-6">
            <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-950 via-slate-900 to-slate-950 border border-indigo-500/30 p-6 md:p-8">
              <div className="absolute top-0 right-0 w-72 h-72 bg-indigo-500/10 rounded-full blur-3xl -mr-10 -mt-10" />
              <div className="relative z-10 max-w-3xl space-y-4">
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-900/50 text-indigo-300 border border-indigo-500/20">SSEAYP Social Contribution Project</span>
                <h2 className="text-3xl font-extrabold text-white">The First KIZUNA Youth Knowledge Expedition</h2>
                <p className="text-slate-300 text-sm leading-relaxed">Through the Ship for Southeast Asian Youth Program (SSEAYP), an international youth research crew will visit remote fishing villages across ASEAN and Japan — collecting oral warning patterns, building local resilience books, and deploying KIZUNA-AI technology across the seas.</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {[["Pilot 1: Vietnam (Coastal)","Tide anomalies, swallow & seaweed warning systems in Central Vietnam fishing communities.","teal"],["Pilot 2: Okinawa, Japan","Cloud patterns, warm winter south winds, and island typhoon indicators from Ryukyu elders.","indigo"],["Pilot 3: ASEAN Regional Hub","Philippines, Indonesia, Thailand consolidation and multilingual educational book rollout.","amber"]].map(([title, desc, color]) => (
                <div key={title} className={`bg-slate-900 border border-${color}-500/20 p-5 rounded-2xl`}>
                  <h5 className={`font-bold text-${color}-400 text-sm mb-2`}>{title}</h5>
                  <p className="text-xs text-slate-400 leading-relaxed">{desc}</p>
                </div>
              ))}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Learn More Card */}
              <div className="bg-slate-900 border border-indigo-500/30 rounded-2xl p-6 flex flex-col gap-4">
                <div>
                  <h4 className="text-lg font-bold text-white mb-1">Learn More About SSEAYP</h4>
                  <p className="text-sm text-slate-400 leading-relaxed">The Ship for Southeast Asian Youth Program (SSEAYP) is a flagship youth exchange initiative led by the Cabinet Office of Japan, connecting young leaders from ASEAN nations and Japan to collaborate on social impact projects every year.</p>
                </div>
                <div className="space-y-3">
                  <a href="https://www.facebook.com/sseaypvn" target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 bg-blue-950/40 hover:bg-blue-950/70 border border-blue-500/30 hover:border-blue-400/50 rounded-xl p-4 transition-all group">
                    <svg className="w-8 h-8 text-blue-400 shrink-0" fill="currentColor" viewBox="0 0 24 24"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>
                    <div>
                      <p className="text-sm font-bold text-white group-hover:text-blue-300 transition-colors">SSEAYP Vietnam</p>
                      <p className="text-xs text-slate-400">facebook.com/sseaypvn</p>
                    </div>
                    <svg className="w-4 h-4 text-slate-500 group-hover:text-blue-400 ml-auto transition-colors" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                  </a>
                  <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 text-xs text-slate-400">
                    <p className="font-bold text-white mb-1">Contact KIZUNA-AI Team</p>
                    <p>Reach us through the SSEAYP Vietnam page above, or connect directly with our pilot team via the SSEAYP national organizing committee in your country.</p>
                  </div>
                </div>
              </div>

              {/* Themes */}
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
                <h4 className="text-sm font-bold text-white">Aligned SSEAYP Discussion Themes</h4>
                <div className="space-y-3">
                  {[["🌿 Global Environment","Registers micro-level ecological details and promotes organic adaptation to micro-climate variations.","teal"],["⚠️ Disaster Risk Reduction","Transforms vulnerable verbal legends into structured hazard triggers complementing scientific radar systems.","amber"],["🤖 Digital Society & AI","Deploys translation models, speech-to-text, and generative AI purely as a repository preservation tool.","indigo"],["📚 Quality Education","Crafts regional bilingual lesson modules, enriching classroom climate science with generational wisdom.","emerald"]].map(([title, desc, color]) => (
                    <div key={title} className={`bg-slate-950 border border-${color}-500/10 p-3 rounded-xl flex gap-3`}>
                      <div>
                        <h5 className={`font-bold text-${color}-400 text-xs mb-0.5`}>{title}</h5>
                        <p className="text-[11px] text-slate-400">{desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ── PROFILE ── */}
        {activeTab === 'profile-center' && (
          <div className="space-y-6">
            <div className="bg-slate-950 border border-slate-800 rounded-3xl p-6 md:p-8">
              <h3 className="text-2xl font-extrabold text-white mb-4">Identity & Access Panel</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
                {Object.entries(mockUsers).map(([key, u]) => {
                  const isSelected = currentUser.username === u.username;
                  const av = getDisplayAvatarFor(u);
                  return (
                    <button key={key} onClick={() => setCurrentUser(u)} className={`text-left p-5 rounded-2xl border transition-all relative ${isSelected ? 'bg-gradient-to-br from-indigo-950 to-slate-950 border-indigo-500' : 'bg-slate-900 border-slate-800 hover:border-slate-700'}`}>
                      {isSelected && <span className="absolute top-3 right-3 text-[10px] font-extrabold uppercase tracking-widest bg-indigo-500 text-slate-950 px-2 py-0.5 rounded-full">Active</span>}
                      <div className="flex items-center gap-3">
                        {av ? <img src={av} alt={u.name} className="w-12 h-12 rounded-full object-cover border-2 border-slate-800" /> : <AvatarIcon gender={u.gender} className="w-12 h-12 rounded-full border-2 border-slate-800" />}
                        <div><h4 className="font-bold text-white text-sm">{u.name}</h4><p className="text-[11px] text-teal-400 font-medium mt-0.5">{u.role}</p></div>
                      </div>
                    </button>
                  );
                })}
              </div>
              <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6 flex flex-col lg:flex-row gap-8 items-start">
                <div className="w-full lg:w-1/4 flex flex-col items-center text-center space-y-3 border-b lg:border-b-0 lg:border-r border-slate-800 pb-6 lg:pb-0 lg:pr-6">
                  <div className="relative group">
                    {(customAvatar || savedAvatars[currentUser.username]) ? (
                      <img src={customAvatar || savedAvatars[currentUser.username]} alt={currentUser.name} className="w-28 h-28 rounded-2xl object-cover border-2 border-teal-500/30 shadow-lg" />
                    ) : (
                      <AvatarIcon gender={currentUser.gender} className="w-28 h-28 rounded-2xl border-2 border-teal-500/30 shadow-lg" />
                    )}
                    <button onClick={() => fileInputRef.current && fileInputRef.current.click()} className="absolute inset-0 bg-slate-950/70 opacity-0 group-hover:opacity-100 transition-opacity rounded-2xl flex flex-col items-center justify-center gap-1 text-white">
                      <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" /><path strokeLinecap="round" strokeLinejoin="round" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
                      <span className="text-[9px] font-bold uppercase">Change photo</span>
                    </button>
                  </div>
                  <input ref={fileInputRef} type="file" accept="image/*" onChange={handleAvatarUpload} className="hidden" />
                  <div className="flex gap-2 flex-wrap justify-center">
                    <button onClick={() => fileInputRef.current && fileInputRef.current.click()} className="text-[10px] font-bold text-teal-400 bg-slate-950 border border-slate-800 hover:border-teal-500/40 px-3 py-1.5 rounded-lg">Upload Photo</button>
                    {customAvatar && <button onClick={() => { setCustomAvatar(null); setAvatarUploadError(""); }} className="text-[10px] font-bold text-amber-400 bg-slate-950 border border-slate-800 px-3 py-1.5 rounded-lg">Discard Draft</button>}
                    {savedAvatars[currentUser.username] && !customAvatar && <button onClick={handleDeleteSavedAvatar} className="text-[10px] font-bold text-red-400 bg-slate-950 border border-slate-800 px-3 py-1.5 rounded-lg">Remove Photo</button>}
                  </div>
                  {avatarUploadError && <p className="text-[10px] text-red-400 max-w-[160px]">{avatarUploadError}</p>}
                  {customAvatar && <p className="text-[10px] text-amber-400 max-w-[160px]">Unsaved — click Save Profile to keep.</p>}
                  <div><h4 className="font-extrabold text-lg text-white">{currentUser.name}</h4><span className="inline-block mt-1 px-3 py-0.5 bg-slate-950 border border-slate-800 rounded-full text-[10px] font-bold text-slate-400 uppercase tracking-wider">@{currentUser.username}</span></div>
                </div>
                <div className="flex-1 space-y-4 w-full">
                  <h4 className="text-sm font-bold text-slate-400 uppercase tracking-widest border-b border-slate-800 pb-1">Profile Details</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                    <div><span className="text-slate-500 font-bold block">ROLE</span><p className="text-teal-400 font-semibold text-sm mt-0.5">{currentUser.role}</p></div>
                    <div><span className="text-slate-500 font-bold block">COUNTRY</span><p className="text-white font-medium mt-0.5">{currentUser.country}</p></div>
                    <div><span className="text-slate-500 font-bold block">EMAIL</span><p className="text-slate-300 font-mono mt-0.5">{currentUser.email}</p></div>
                    <div><span className="text-slate-500 font-bold block">PHONE</span><p className="text-slate-300 mt-0.5">{currentUser.phone}</p></div>
                  </div>
                  <div className="text-xs pt-2">
                    <span className="text-slate-500 font-bold block mb-1">BIOGRAPHY</span>
                    <textarea rows={3} value={bioDraft} onChange={e => setBioDraft(e.target.value)} className="text-slate-300 leading-relaxed bg-slate-950 p-3 rounded-xl border border-slate-800 w-full focus:outline-none focus:border-teal-500" />
                  </div>
                  <div className="flex items-center gap-3 pt-1">
                    <button onClick={handleSaveProfile} disabled={isSavingProfile} className="bg-gradient-to-r from-teal-500 to-emerald-500 text-slate-950 font-bold px-5 py-2.5 rounded-xl text-xs disabled:opacity-50 flex items-center gap-2">
                      {isSavingProfile ? (<><svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>Saving...</>) : "Save Profile"}
                    </button>
                    {profileSavedMsg && <span className="text-[11px] text-emerald-400 font-semibold">{profileSavedMsg}</span>}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

      </main>

      <footer className="bg-slate-950 text-slate-500 text-xs py-6 border-t border-slate-800/50 text-center space-y-2 px-6">
        <p className="font-medium text-slate-400">"Technology preserves knowledge. Youth preserve connections. Together, they build resilient communities."</p>
        <p>KIZUNA-AI Platform © 2026 · Inspired by SSEAYP Heart-to-Heart and Gen-to-Gen values.</p>
      </footer>
    </div>
  );
}
